/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink\ble_sdk_2_02_06_07\blelib\host\host_pxxx_sc.a"
"C:\ti\simplelink\ble_sdk_2_02_06_07\blelib\ctrl\cc2640\cc2640_ctrl_pxxx_ext_sc.a"
"C:\ti\simplelink\ble_sdk_2_02_06_07\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none_v41_v42.a"
